project:
  type: website

website:
  title: "Not Entirely Unambiguous"
  navbar:
    left:
      - text: "Posts"
        href: posts/index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    number-sections: true
    mainfont: "Lora"
    monofont: "Source Code Pro"

execute:
  freeze: auto



